### ISSUE TITLE
Throws error when installing

### ISSUE THREAD

**Issue by Francaolisa** [ourarash/crypto-aggregator#6]
Hi, trying to install with command but it throws an error npm install crypto-aggregator --save

Here's the error

npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/ourarash/get-cursor-position.git
npm ERR! ssh: Could not resolve hostname github.com: Name or service not known
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!   
PS C:\Users\Fran\crypto-aggregator> npm install crypto-aggregator --save
npm WARN deprecated request@1.9.9: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
npm ERR! path 
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.5 found at "C:\Users\Fran\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v15.4.0/node-v15.4.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v15.4.0/node-v15.4.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v15.4.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v15.4.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v15.4.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v15.4.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v15.4.0/win-x86/node.lib
npm ERR! gyp http 404 https://nodejs.org/download/release/v15.4.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v15.4.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v15.4.0/win-x64/node.lib
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS

**Comment by ourarash** [comment]
`Could not resolve hostname github.com `

Sounds like you have an issue with ssh connection to github. This link might help: https://dsolc.com/blogs/7-ssh-could-not-resolve-hostname-github-error/
